# Generated by Django 4.2.1 on 2023-05-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_address_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='store.customer'),
        ),
    ]
