# Generated by Django 4.2.1 on 2023-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cartitem_added_time_alter_address_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(default='-', max_length=265),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-29T20:13:19.755332Z'),
            preserve_default=False,
        ),
    ]
