# Generated by Django 4.2.1 on 2023-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_payment_url_alter_cartitem_added_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'ORDER_STATUS_PENDING'), ('C', 'ORDER_STATUS_COMPLETE'), ('F', 'ORDER_STATUS_FAILED')], default='P', max_length=1),
        ),
    ]
