# Generated by Django 4.2.1 on 2023-06-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/image')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='store.products')),
            ],
        ),
    ]
