# Generated by Django 4.2.1 on 2023-06-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productsimage_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url_for_admin',
            field=models.CharField(default='-', max_length=265),
        ),
    ]
