# Generated by Django 4.2.1 on 2023-06-22 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_payment_url_for_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
